import { Colors } from "@/src/utils/colors";
import { FONTS } from "@/src/utils/storeData";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  background: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 15,
    paddingBottom: 30,
    gap: 14,
  },
  introCard: {
    backgroundColor: Colors.primarylite,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.lightprimary1,
    gap: 6,
  },
  introTitle: {
    fontSize: 15,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  introText: {
    fontSize: 13,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    lineHeight: 19,
  },
  typeCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  typeCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  typeIconBox: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  typeIcon: {
    width: 22,
    height: 22,
  },
  typeTexts: {
    flex: 1,
    gap: 3,
  },
  typeTitle: {
    fontSize: 15,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  typeSubtitle: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  rightIcon: {
    width: 18,
    height: 18,
    tintColor: Colors.darkText,
  },
  sectionCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  sectionHint: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    lineHeight: 18,
  },
  photoRow: {
    flexDirection: "row",
    gap: 12,
  },
  photoSlot: {
    flex: 1,
    aspectRatio: 0.72,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.Boxgray,
    borderStyle: "dashed",
    backgroundColor: Colors.litegray1,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  photoSlotFilled: {
    borderStyle: "solid",
    borderColor: Colors.primary,
    backgroundColor: Colors.white,
  },
  photoPreview: {
    width: "100%",
    height: "100%",
  },
  photoPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 10,
  },
  photoPlaceholderIcon: {
    width: 28,
    height: 28,
    tintColor: Colors.primary,
  },
  photoLabel: {
    fontSize: 13,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
    textAlign: "center",
  },
  photoAction: {
    fontSize: 11,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    textAlign: "center",
  },
  retakeBtn: {
    position: "absolute",
    bottom: 8,
    alignSelf: "center",
    backgroundColor: Colors.transparant,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  retakeText: {
    fontSize: 12,
    fontFamily: FONTS.Medium,
    color: Colors.white,
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  progressChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.litegray1,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
  },
  progressChipDone: {
    backgroundColor: Colors.litegreen,
    borderColor: Colors.green,
  },
  progressChipText: {
    fontSize: 11,
    fontFamily: FONTS.Medium,
    color: Colors.darkText,
  },
  progressChipTextDone: {
    color: Colors.green,
  },
  addPhotoBtn: {
    height: 52,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.primary,
    backgroundColor: Colors.primarylite,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  addPhotoBtnText: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.primary,
  },
  addPhotoIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.primary,
  },
  thumbGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  thumbWrap: {
    width: 88,
    height: 88,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.Boxgray,
  },
  thumbImage: {
    width: "100%",
    height: "100%",
  },
  thumbRemove: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.transparant,
    alignItems: "center",
    justifyContent: "center",
  },
  thumbRemoveIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.white,
  },
  field: {
    gap: 8,
  },
  label: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  required: {
    color: Colors.red,
  },
  dateField: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1.2,
    paddingHorizontal: 15,
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    backgroundColor: Colors.white,
    borderColor: Colors.Boxgray,
  },
  dateFieldActive: {
    borderColor: Colors.primary,
  },
  dateIcon: {
    width: 22,
    height: 22,
  },
  dateText: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.black,
  },
  datePlaceholder: {
    fontSize: 14,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  calendarModal: {
    width: "100%",
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 15,
    alignSelf: "center",
  },
  error: {
    fontSize: 13,
    color: Colors.red,
    fontFamily: FONTS.Regular,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
  },
  secondaryBtn: {
    flex: 1,
    height: 44,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: Colors.primary,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.primary,
  },
  docCard: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.Boxgray,
    gap: 4,
  },
  docCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  docCardTexts: {
    flex: 1,
    gap: 4,
  },
  docTitle: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.black,
  },
  docMeta: {
    fontSize: 12,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
  },
  emptyText: {
    fontSize: 13,
    fontFamily: FONTS.Regular,
    color: Colors.darkText,
    textAlign: "center",
    paddingVertical: 8,
  },
  retryBtn: {
    alignSelf: "center",
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 7,
    backgroundColor: Colors.primary,
  },
  retryBtnText: {
    fontSize: 14,
    fontFamily: FONTS.SemiBold,
    color: Colors.white,
  },
});
