
import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { heightPercentageToDP } from "react-native-responsive-screen";
import { Colors } from "../../utils/colors";
import { FONTS } from "../../utils/storeData";
  
  export const styles = StyleSheet.create({
    dateInput: {
      // width: widthPercentageToDP(90),
      height: heightPercentageToDP(7),
      backgroundColor: Colors.white,
      borderRadius: 10,
      borderColor: Colors.litegray,
      borderWidth: 1,
      paddingHorizontal: 15,
      alignItems: "center",
      marginTop: 5,
      flexDirection: "row",
      // marginHorizontal: 20,
      marginBottom: 10,
      justifyContent: "space-between",
      // marginHorizontal: 20,
    },
    dateText: {
      fontSize: 14,
      color: Colors.black,
      fontFamily: FONTS.Regular,
    },
    modalContainer: {
      backgroundColor: "white",
      padding: 20,
      borderRadius: 10,
    },
    // title: {
    //   fontSize: 20,
    //   marginBottom: 10,
    //   textAlign: "center",
    // },
    row: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
    },
    decadeButton: {
      padding: 10,
      backgroundColor: "#f0f0f0",
      margin: 5,
      borderRadius: 5,
    },
    yearButton: {
      padding: 10,
      backgroundColor: "#f0f0f0",
      margin: 5,
      borderRadius: 5,
    },
    monthButton: {
      padding: 10,
      backgroundColor: "#f0f0f0",
      margin: 5,
      borderRadius: 5,
    },
    selected: {
      backgroundColor: Colors.primary,
    },
    selectedDateText: {
      fontSize: RFValue(14),
      fontFamily: FONTS.Medium,
      color: Colors.black,
      marginTop: RFValue(5),
      // marginHorizontal: 20,
    },
    button: {
      padding: 10,
      backgroundColor: Colors.primary,
      margin: 5,
      borderRadius: 5,
      alignItems: "center",
    },
    navigation: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 10,
    }, ///
    result: {
      fontSize: 18,
      textAlign: "center",
    },
    safe: {
      flex: 1,
      backgroundColor: Colors.white,
    },
    wellcome: {
      fontSize: RFValue(17),
      fontFamily: FONTS.SemiBold,
      color: Colors.black,
      marginTop: 40,
    },
    dis: {
      fontSize: RFValue(14),
      fontFamily: FONTS.Regular,
      color: Colors.textgray,
      marginTop: 8,
      marginBottom: 15,
    },
    logo: {
      alignSelf: "center",
      marginTop: RFValue(40),
    },
    container: {
      paddingHorizontal: 24,
    },
    subContainer: {
      flex: 1,
    },
    dropdownButtonStyle: {
      height: RFValue(45),
      borderWidth: 1,
      borderColor: Colors.litegray,
      width: "100%",
      borderRadius: 7,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 12,
      marginTop: RFValue(5),
    },
    dropdownButtonTxtStyle: {
      flex: 1,
      fontSize: 14,
      fontFamily: FONTS.Regular,
      color: Colors.black,
    },
    dropdownMenuStyle: {
      backgroundColor: Colors.white,
      borderRadius: 8,
      fontFamily: FONTS.Regular,
      color: Colors.black,
    },
    dropdownItemStyle: {
      width: "100%",
      flexDirection: "row",
      paddingHorizontal: 12,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 8,
    },
    dropdownItemTxtStyle: {
      flex: 1,
      fontSize: 14,
      fontFamily: FONTS.Regular,
      color: Colors.black,
    },
    title: {
      fontSize: RFValue(16),
      fontFamily: FONTS.Regular,
      color: Colors.black,
      alignSelf: "center",
      marginVertical: RFValue(15),
    },
    error: {
      color: Colors.red,
      fontSize: RFValue(10),
      fontFamily: FONTS.Regular,
      marginTop: RFValue(1),
    },
    mview: {
      paddingHorizontal: 20,
      justifyContent: "center",
      alignItems: "center",
      margin: 0,
      backgroundColor: Colors.transparant,
    },
    mcontainer: {
      flex: 1,
      position: "absolute",
      borderRadius: 26,
      backgroundColor: "#F9FDFF",
      width: "100%",
      overflow: "hidden",
    },
    textInputContainer: {
      height: RFValue(45),
      borderWidth: 1,
      borderColor: Colors.litegray,
      borderRadius: 10,
      alignItems: "center",
      paddingHorizontal: 10,
      marginTop: RFValue(5),
      color: Colors.black,
      fontFamily: FONTS.Regular,
    },
    textInput: {
      fontSize: 15,
      color: Colors.black,
      fontFamily: FONTS.Regular,
      paddingLeft: 35,
      backgroundColor: "transparent",
    },
    predefinedPlacesDescription: {
      color: "#1faadb",
      color: Colors.black,
      fontFamily: FONTS.Regular,
    },
    address: {
      flex: 1,
      color: Colors.black,
      fontFamily: FONTS.Regular,
    },
    error: {
      color: Colors.red,
      fontSize: RFValue(10),
      fontFamily: FONTS.Regular,
      marginTop: RFValue(1),
    },
  
    option: {
      padding: 10,
      color: Colors.black,
    },
    searchInput: {
      height: RFValue(40),
      borderColor: Colors.litegray,
      borderWidth: 1,
      borderRadius: 5,
      margin: RFValue(10),
      paddingHorizontal: RFValue(10),
      fontSize: RFValue(14),
      fontFamily: FONTS.Regular,
    },
    galleryimagebg: {
      width: 342,
      height: 50,
      borderWidth: 1,
      borderColor: Colors.litegray,
      borderRadius: 10,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
    },
    galleryicon: {
      height: 24,
      width: 24,
    },
    gallerytext: {
      color: Colors.black,
      fontFamily: FONTS.Regular,
      paddingLeft: 5,
    },
    cameraimagebg: {
      width: 342,
      height: 50,
      borderWidth: 1,
      borderColor: Colors.litegray,
      borderRadius: 10,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
    },
    modal: {
      justifyContent: "flex-end",
      margin: 0,
      backgroundColor: Colors.transparant,
    },
    modalcontainer: {
      flex: 1,
      position: "absolute",
      bottom: 0,
      borderTopRightRadius: 30,
      borderTopLeftRadius: 30,
      backgroundColor: Colors.white,
      width: "100%",
      paddingTop: 20,
      paddingBottom: 35,
    },
    modalheader: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 24,
    },
    headertext: {
      borderBottomWidth: 1,
      borderColor: Colors.black,
      color: Colors.black,
      fontSize: 17,
      paddingBottom: 15,
    },
    profilemodalheader: {
      height: 380,
      width: 380,
      backgroundColor: "#E0F0FF",
      borderRadius: 200,
      position: "absolute",
      top: -210,
      alignSelf: "center",
    },
    userimage: {
      height: 100,
      width: 100,
      alignSelf: "center",
      marginTop: 30,
    },
    remindmenexttext: {
      height: RFValue(41),
      width: "82%",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 10,
      marginTop: RFValue(10),
      marginBottom: RFValue(30),
      borderWidth: 1,
      borderColor: Colors.litegray,
    },
  });
  