export const Colors = {
  black: "#000000",
  inActive:"#A5A6A9",
  white: "#FFFFFF",
  primary: "#4E83E7",
  primaryblue: "#4E75B9",
  primaryopacity: "#EEF3FD",
  Boxgray: "#DFE5EA",
  textgray: "#9D9D9D",
  litegray: "#E7E7E7",
  litegray1: "#F2F2F2",
  red: "#FF0000F2",
  pink: "#EF5A7E",
  primarylite: "#EDF3FD",
  transparant: "rgba(0,0,0,0.5)",
  green: "#06AC14",
  litegreen: "#E7F7E8",
  neworder: "#FF005EF2",
  neworderlite: "#FFE6EF",
  plan: "#7C00FFF2",
  planlite: "#F2E6FF",
  finished: "#0037FFFC",
  finishedlite: "#E6EBFF",
  postponed: "#00D0FFF2",
  postponedlite: "#E6FBFF",
  hold: "#00FF22F2",
  holdlite: "#E6FFE9",
  approve: "#FF6200F2",
  approvelite: "#FFF0E6",
  dicline: "#FF0000F2",
  diclinelite: "#FFE6E6",
  invoice: "#FFEB3BF2",
  invoicelite: "#FFFDEC",
  iconbg: "#CADAF8",
  lightprimary: "#4E83E750",
  lightprimary1: "#DCE6FA",
  vibrantblue: "#007bff",
  border: "#BBBBBB",
  blue1: "#1E90FF",
  gray: 'gray',
  orrange: 'orange',
  yellow: 'yellow',
  user: '#fdac41',
  commentBg: '#FFF8C8',
  disbled: '#FFFBEB',
  Boxgray: "#DFE5EA",
  textgray: "#9D9D9D",
  litegray: "#E7E7E7",
  litegray1: "#F2F2F2",
  litegray2: "#ededed",
  hold:'#cfe2ff',
  closed:'#caffe5',
  normal:'#fffbde'

};
//     #fffbde(normal)
// #cfe2ff(hold)
// #caffe5(closed)